### ISSUE TITLE
security hole

### ISSUE THREAD

**Issue by francescoagati** [Steveorevo/node-red-contrib-nbrowser#1]
nightmare use electron and in some case can open securty holes on the maschine where node-red run
https://github.com/segmentio/nightmare/pull/1234

**Comment by Steveorevo** [comment]
Correct. It is NOT sandboxed. Suggest adding a warning to the readme (and don't load malicious websites) :)

**Comment by Steveorevo** [comment]
Documentation updated in f66066d24a7162ffeb5f0752090cc9eec5252c88
