### ISSUE TITLE
not working on ubuntu

### ISSUE THREAD

**Issue by igisho** [Steveorevo/node-red-contrib-nbrowser#11]
Hi, nbrowser node is installed int node-red correcly eather via palettemanager or via console but after i place node into flow. and deploy it i get error. 

Flows stopped due to missing node types.
nbrowser

tried on several installs of ubuntu Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

**Comment by mito** [comment]
i this it is because of ubuntu not having latest node.js in default repos

**Comment by Steveorevo** [comment]
What version of node.js are you using? On the command line type:
```
node -v
```

**Comment by igisho** [comment]
Hi firs part of problem was in wrong node version. Now im using v8.10.0 but nbrowser node always stuck at some method. Status of node sasy for example: running:gotoURL and nothing is happening.

**Comment by mito** [comment]
If  I put multiple methods in node, it seems like it is stuck always on last one.

**Comment by igisho** [comment]
Version of operating system:

Distributor ID:  Ubuntu
Description:      Ubuntu 16.04.4 LTS
Release:            16.04
Codename:       xenial

**Comment by igisho** [comment]
node -v: v8.11.0
npm -v:   5.6.0
Node-RED version: v0.18.4

**Comment by mito** [comment]
tried different versions of nodejs and electron, no difference 
also tried running electrons quickstart and simple examples, everything ends with exit code 1

**Comment by Steveorevo** [comment]
Electron is based on Chromium. Let’s see if you have the prerequisites to run a viable browser; do you have a desktop with a version of Chrome browser running successfully?

**Comment by mito** [comment]
ok, i seems it is running on ubuntu Desktop, my previous tries were on ubuntu server, is it possible to run it on headless server?

**Comment by mito** [comment]
this is working  xvfb-run node-red

**Comment by mito** [comment]
here you can find more info on nightmare/electron on headless server 
https://github.com/segmentio/nightmare/issues/224

**Comment by Steveorevo** [comment]
Closing for now; duplicate question/issue for 

https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/5

Thank you for your feedback
