### ISSUE TITLE
Cant install on Raspberry Pi

### ISSUE THREAD

**Issue by blackwellj** [Steveorevo/node-red-contrib-nbrowser#12]
Hi, when I try and install on my pi i get this error
![nbrowser](https://user-images.githubusercontent.com/12017222/38452548-440a9abe-3a3e-11e8-9d5d-e9852217ce3d.jpg)

Can anyone help?

**Comment by Steveorevo** [comment]
Did you try removing the offending directory manually?

**Comment by blackwellj** [comment]
Yes I tried that, from don’t some reading I don’t think some of the dependencies are pi compatible :(

James Blackwell

On 13 Apr 2018, at 20:32, Stephen J. Carnam <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try removing the offending directory manually?

**Comment by blackwellj** [comment]
I have but didn’t really understand them. What I really need is a step by step guide

James Blackwell

On 17 Apr 2018, at 08:17, Stephen J. Carnam <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you check our existing closed issues from other Pi users; requirements, window manager:virtual x window, electron on Pi, dependencies, etc.

#7<https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/7>

**Comment by Steveorevo** [comment]
It also looks like your version of node is not supported. The first line in your error is a complaint about node 4; you need node 8 or above.

**Comment by blackwellj** [comment]
I beleive I’m running the latest version of node red

James Blackwell

On 27 May 2018, at 23:11, Stephen J. Carnam <notifications@github.com<mailto:notifications@github.com>> wrote:


It also looks like your version of node is not supported. The first line in your error is a complaint about node 4; you need node 8 or above.

**Comment by Steveorevo** [comment]
The error message is complaining about node (the engine that runs node-red). The node engine does not meet the requirements; otherwise the message would not appear.
