### ISSUE TITLE
Install on IBM Bluemix running Node-Red

### ISSUE THREAD

**Issue by spatel626** [Steveorevo/node-red-contrib-nbrowser#16]
Is is possible to run this on a node-red server running in the cloud? 

I was able to get the node-red-contrib-nbrowser installed but I get no response when trying to so a simple HTML source output.

It works when I run it on my local machine so I was wondering is there is anyway to make it work on the cloud.

**Comment by Steveorevo** [comment]
See last comment in https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/5

You need a “window manager” or could install xvfb.
