### ISSUE TITLE
How to get all cookies 

### ISSUE THREAD

**Issue by cyberindy** [Steveorevo/node-red-contrib-nbrowser#18]
Is it possible to extract all the cookies at once if I don't know their namens?
Nightmare seems to support this. 
Thanks a lot for your work!

**Comment by Steveorevo** [comment]
You should be able to do this via JavaScript (see link below); using nbrowser's evalJavaScript method to retrieve the output.

https://stackoverflow.com/questions/3400759/how-can-i-list-all-cookies-for-the-current-page-with-javascript
