### ISSUE TITLE
Closing the instance

### ISSUE THREAD

**Issue by KeiyaD** [Steveorevo/node-red-contrib-nbrowser#19]
I noticed that when executing a "getHTML" throws a timeout the instance does not close. and If I have a periodic execution of nbrowser, then the instances keep stacking up. Is there a option to close the instance if there is an error, timeout, warning or even closing by input?

**Comment by Steveorevo** [comment]
Make sure the "Close instance after methods?" is checked. Somewhere along the flow there should be a reference to the instance with the "Close instance after methods?" checked to close it.

**Comment by KeiyaD** [comment]
I have it checked. This is the configuration.

![image](https://user-images.githubusercontent.com/50403201/57429154-7f839200-722b-11e9-802a-016221641542.png)

Any more ideas on what I can do? 
In case of an error, search the process and kill it?

It would also be good if there was a possibility to have a GOTO statement in the flow to keep the nbrowser in a loop instead of calling a new instance every time.

I wish this node would have some additional functionalities :)

**Comment by Steveorevo** [comment]
The instance is kept in the msg.nbrowser variable in the flow. After the timeout, does the flow continue to another node? If so, simply placing another nbrowser with the same msg.nbrowser will recycle/use that instance. It should be possible to close the instance. 

If the issue persists; could you post a simplified flow that shows the issue for me to reproduce?

**Comment by KeiyaD** [comment]
> The instance is kept in the msg.nbrowser variable in the flow
I did not know that. That opens some new possibilities for me! I have to check that out!
I'll try it out and report back! Thanks!

**Comment by KeiyaD** [comment]
> The instance is kept in the msg.nbrowser variable in the flow. After the timeout, does the flow continue to another node? If so, simply placing another nbrowser with the same msg.nbrowser will recycle/use that instance. It should be possible to close the instance.
> 
> If the issue persists; could you post a simplified flow that shows the issue for me to reproduce?

I looped the browser and it works like a charm! 
![image](https://user-images.githubusercontent.com/50403201/57506425-13bd2a00-72fc-11e9-90a9-c509acae98da.png)
