### ISSUE TITLE
Node-Red crashes getting TypeError:Cannot read property of undefined at nbrowser.js 367:19

### ISSUE THREAD

**Issue by Gippsman2017** [Steveorevo/node-red-contrib-nbrowser#24]
Hi,
I am getting Getting TypeError:Cannot read property of undefined at nbrowser.js 367:19 and it bombs out node-red completely.
**I have installed nbrowser with no errors**, xvfb-run is installed, as is nightmare and electron.
I have tested both it running on both debian stretch and redhat 7.6 and both give the same error.
Using  xvfb-run  --listen-tcp wget https://www.google.com.au returns the index file correctly.
However, running the example in nightmare returns nothing and it completely failes in the make file.
So, exactly where to test next is a little elusive, can you please point me in the right direction to help this issue.
Many thanks.

**Comment by Steveorevo** [comment]
May want to post in nightmarejs. Are there any other errors or info running the example in nightmare. A make error tells us that you maybe missing additional dependencies needed to have nightmare functional. 

Did you follow the items mentioned in https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/17 ?

**Comment by Gippsman2017** [comment]
Yep, thanks finally tracked it down it was a multitude of container config problems and libraries (RPM's) missing, there are just so many possible issues you must have to contend with to fault find this app although once I learned how electron and nightmare work under the covers it was easier, ...great app though !!
