### ISSUE TITLE
Not opening a browser 

### ISSUE THREAD

**Issue by mathurv** [Steveorevo/node-red-contrib-nbrowser#29]
When I selected "Show browser window instance" I am not seeing any browser window on Linux 18.04
Whether I select the above check box or not, it is getting stuck at the same place as explained below.
It is getting stuck showing message "running: going to URL" with a green dot.

**Comment by Steveorevo** [comment]
Which browser are you viewing the flow through? Keep in mind that the browser you are viewing Node-RED is different from the browser being launching in the Linux's desktop manager instance (which your linux instance must have -unless you use xvfb).

**Comment by luetter82** [comment]
Hi, i use chrome to view the node red flow in hassio, but currently i dont see a browser which show the website.
what can i do to see the called website in node red?

**Comment by Steveorevo** [comment]
Are you on the node-red server itself? Does it have a window manager installed or is it a headless server? Which operating system?

**Comment by luetter82** [comment]
i use hassio with nodered on an rasp 3 on ubuntu. i dont install a windows manager

**Comment by Steveorevo** [comment]
See the sticky post issue: https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/17#issuecomment-473386507
