### ISSUE TITLE
Stuck with "running: gotoURL"

### ISSUE THREAD

**Issue by stevenhorner** [Steveorevo/node-red-contrib-nbrowser#31]
Not Sure if I'm doing something wrong but running Node-Red on a Headless Ubuntu server. Installed nbrowser node via the palette and restarted.

If I inject a url the nbrowser node, displays `running: gotoURL` and nothing ever happens, it just stays with that message. I have a debug node connected but nothing is displayed.

I can't see anything is happening and no errors are displayed.

Maybe I am missing something obvious?

Does someone have a simple example flow I can copy and paste in to check if it is working just in case its me?

**Comment by Steveorevo** [comment]
You cannot run completely "headless"; please see the pinned issue/question or see: 

https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/17#issuecomment-434083072
