### ISSUE TITLE
Self signed certificate work around.

### ISSUE THREAD

**Issue by nprowler** [Steveorevo/node-red-contrib-nbrowser#4]
Attempt to access a self-signed certificate website, the Electron browser passes
back a details: **"ERR_INSECURE_RESPONSE"** error and hangs.

Steve's workaround solves this problem.

edit nbrowser.js  Line 33:

              }
to
                  },
                   switches: {
                     ‘ignore-certificate-errors’: true
                   }

**Comment by Steveorevo** [comment]
Updated in version 1.1.0. At the bottom of the settings panel is a new option to ignore ssl certificate errors.
