### ISSUE TITLE
Methods configurator broken

### ISSUE THREAD

**Issue by pokryva** [Steveorevo/node-red-contrib-nbrowser#6]
This is how nbrowser's node config windows looks like - the Methods section is broken:
![image](https://user-images.githubusercontent.com/15121868/34975842-089dbb26-fa94-11e7-9dda-c8e3b4e979fa.png)

Node & Node-RED are running on windows 7 or debian 9
node --version --> v8.9.4
npm --version --> 5.6.0
node-red-contrib-nbrowser -->  1.1.0

Tested in Chrome 63.0.3239.132 / FireFox 57.0.4 / IE 11

**Comment by Steveorevo** [comment]
This appears to be a simple CSS margin error; will try to reproduce. Try changing with width:165px to be width 155px on line 812 in nbrowser.html to read:

```
var selectField = $('<select/>',{class:"node-input-method-type",style:"width:155px; margin-right:10px;"}).appendTo(row);
```

**Comment by pokryva** [comment]
OK, thank you for the direction, in fact I had to "hack" the width value even further down to 145 to make it properly alligned. Thanks!

**Comment by Steveorevo** [comment]
Noted. Thank you for contributing. Will post changes to the main repo shortly.
