### ISSUE TITLE
nbrowser on Raspberry Pi not doing anything

### ISSUE THREAD

**Issue by nospam2k** [Steveorevo/node-red-contrib-nbrowser#7]
I'm just trying to set up a simple inject url to nbrowser node and output to debug and I'm getting nothing. Is there something specific I need to do/not do? I'm running on cli only installation of node-red with node.js 8.9.4.

Ok, now I'm really confused. Just tried on a work existing installation of node-red on my mac and the same thing.

Inject with payload of http://www.google.com -> nbrowser (instance: msg.nbrowser, no show, no methods, no close, ignore ssl) -> debug msg.payload.

If I enable show, I get a pop up (on mac) Electron, but it's blank.

In console, I get an error nbrowser [object Object] and in debug panel: Error: "Error: Evaluation timed out after 30000msec. Are you calling done() or resolving your promises?"

Ok. Getting somewhere: I realized that "built in default gotoUrl" only means that the node is created with that method. My first node was the demo import from credentials and working backwards to when I saw "built-in" I assumed that I could delete all methods.

Sooo... 

With the gotoUrl method that works on my mac both with and without show browser, but not on my raspberry pi 3, so my original question remains as is.

**Comment by Steveorevo** [comment]
Unfortunately this might be related to lack of ARM processor support for Raspberry Pi. However, a recent as 1 month ago, it looks like some progress was made to get Electron working on Raspian "Stretch", the latest Raspberry Pi OS updated just last November. 

https://stackoverflow.com/questions/31927337/electron-not-working-on-raspberry-pi

What OS are you running? A commentator mentioned having to perform a build elsewhere to get electron running.

https://github.com/electron/electron/issues/10468

**Comment by nospam2k** [comment]
Linux raspberrypi 4.9.76-v7+ #1076 SMP Wed Jan 10 17:34:49 GMT 2018 armv7l GNU/Linux

**Comment by Steveorevo** [comment]
>>> I'm running on cli only installation of node-red 

Sorry I missed that part. Unfortunately a CLI install will need further dependencies. See https://github.com/Steveorevo/node-red-contrib-nbrowser/issues/5

As you'll need at least Xvfb (a X virtual framebuffer / window manager) to simulate the needed environment that's requirement for NightmareJS and it's Electron dependencies.

**Comment by nospam2k** [comment]
Sorry, I neglected to close this. the Xvfb did resolve my problem as far as I can remember but had problems with headless authentication with Amazon. I've kind of went in another direction so I'm not positive. I'll close this for now.
