### ISSUE TITLE
interrupted browser behavior when running 2 flows concurrently

### ISSUE THREAD

**Issue by chuyaguo2014** [Steveorevo/node-red-contrib-nbrowser#9]
I am trying to use `nbrowser` to crawl some websites and I realized that, if I run 1 crawl at a time, everything works; but if I kick off the 1st crawl and then the 2nd one shortly afterwards, looks like the browser immediately starts the 2nd crawl and completely aborts everything it was doing in the first crawl. 

Looks like the browser instance is somewhere shared across the flows - Is this an intended functionality of nbrowser where only 1 flow is expected to use the `nbrowser` node at a time? Or am I missing something obvious?

Here's how you can reproduce the issue:
I made 2 gists from the flows - they are crawling the same website except that:
-  [the 1st gist](https://gist.github.com/chuyaguo2014/dbc920849029a0d76f3d7c37eb294c0b) will save the results into a file called `apply2jobs-lifespan-corp-original.html` 
- [the 2nd gist](https://gist.github.com/chuyaguo2014/32a39791612aba68c935575e0f7e161d) will save a file called `apply2jobs-lifespan-corp-copy.html`

_(please let me know if you have issue running the flows in the gist. Thank you!)_

**Comment by Steveorevo** [comment]
If you would like to use more than one instance, did you try changing the instance name in the second field from `msg.nbrowser` to `msg.nbrowser2`? In theory, you could can store the window instance name in a custom variable name of your choosing. Just be sure that any subsequent nbrowser nodes reference it to act upon it; most importantly the close operation to free the variable.

**Comment by chuyaguo2014** [comment]
It worked! Thank you so much! :)

**Comment by chuyaguo2014** [comment]
@Steveorevo 
oops sorry one more question I forgot to mention - Even though "*I can store the window instance name in a custom variable name*", within the same flow, I would still only have 1 window instance, right?

Here is why I'm asking:

I'm thinking about wrapping some of the common browser behaviours into a subflow (something like "go to a page, wait for a selector to appear, click it, save the HTML, and go back"). And I plan to use the `nbrowser` node inside of this subflow. 

And outside of the subflow, I would give it different input (for the start URL, for example), and kick off the crawls. 

Here's an example:
![image](https://user-images.githubusercontent.com/9753313/36396425-25663374-158c-11e8-8964-c49c418931e1.png)


Even though I can store the window instance name like `msg.subflow_nbrowser`, there will still only be 1 place where I set it (i.e. inside the subflow when I first initialize the `nbrowser` node) - does this mean, given the subflow design, I can still only run 1 crawl at a time? 

I know I can kick off multiple crawls in multiple windows if I don't use subflows. I was just wondering if this is also possible with subflow. (my intuition is telling me "no" but I am not an expert in this area so I thought I'd ask). :) 

Thank you so much!

**Comment by Steveorevo** [comment]
Depends how you create the instances along a wire. If you created unique instances outside of the subflow; the subflow could act on the "nbrowser" instance internally (three times). 
<img width="710" alt="screen shot 2018-02-19 at 1 29 19 pm" src="https://user-images.githubusercontent.com/635399/36397909-65698862-1579-11e8-9076-0ab8e520049e.png">

**Comment by chuyaguo2014** [comment]
oh I see! that makes a lot of sense! Thank you so much!
